- name: variable declare
  hosts: localhost
  vars:
    COURSE: "devops"
    DURATION: "120h"
  tasks:
  - name: print info
    ansible.builtin.debug:
      mgs: "course_is {{COURSE}}, Duratioms is {{DURATION}}"