- name: variable declare
  hosts: localhost
  vars:
    COURSE: devops
    DURATION: 120h
  task:
  - name: print info
    ansible.builtion.debug:
      mgs: course is: "{{COURSE}}, Duratioms is {{DURATION}}"