- name: data types
  hosts: localhost
  become: yes
  tasks:
  - name: print onfo
    course: devops with aws #string
    tools: # lists
    - linux
    - terrafom
    - docker
    duration: #map or dicstionary and number
      devops: 30
      linux: 10
      aws: 20
    certified: yes #boolean
  ansible.builtin.debug:
    msg: "{{course}}, {{tootls}}, {{duration}}, {{certified}}"
